name: PyAction Hello World
description: This actions says Hello to you!
author: John Doe

branding:
  icon: check
  color: blue

runs:
  using: docker
  image: Dockerfile

inputs:
  github_token:
    description: The GitHub auth token
    default: ${{ github.token }}
    required: true

  repository:
    description: The repository name in the form of "<owner>/<repo>"
    default: ${{ github.repository }}
    required: true

  name:
    required: false
    description: the person/thing you want to greet
    default: World

outputs:
  phrase:
    description: output message
