[project]
name = "pyaction-hello-world"
version = "0.0.1"
description = "This actions says Hello to you!"
readme = "README.md"
requires-python = ">=3.12"
dependencies = ["pyaction==0.8.1"]

[project.optional-dependencies]
cli = ["pyaction[cli]==0.8.1"]
