name: Greeting

on:
  issues:
    types: [opened]

jobs:
  Build:
    runs-on: ubuntu-latest

    name: Running the action
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Providing variables
        id: provider
        uses: ./
        with:
          issue_number: ${{ github.event.issue.number }}

      - name: Echoing variables
        run: echo ${{ steps.provider.outputs.phrase }}
